@startuml

namespace net.chat #EEEEEE {
  interface IChat {
    -conexion
    -room
    +connect()
    +disconnect()
    +joinRoom()
    +createRoom()
    +leaveRoom()
    +message()
    +userList()
  }
  IChat <|-- ChatMatrix
  IChat <|-- ChatIRC
  IChat <|-- ChatWhatsapp
}

class ChatFabrica {
  -IChat
  +getConexion()
}

ChatFabrica <|-- net.chat

class Principal {
  +main()
}

Principal <|-- ChatFabrica

@enduml
